### ISSUE TITLE
Caused by: javax.crypto.AEADBadTagException

### ISSUE THREAD

**Issue by udayTechnosouls** [kishandonga/EasyPrefs#9]
I got crashed when read 
` if (Prefs.securely().read().content("IsLoginEnable", false)) {`

**Error is** 

 java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
                                         	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:618)
                                         	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
                                         Caused by: java.lang.reflect.InvocationTargetException
                                         	at java.lang.reflect.Method.invoke(Native Method)
                                         	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
                                         	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103) 
                                         Caused by: javax.crypto.AEADBadTagException
                                         	at android.security.keystore2.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:632)
                                         	at javax.crypto.Cipher.doFinal(Cipher.java:2114)
                                         	at com.google.crypto.tink.integration.android.AndroidKeystoreAesGcm.decryptInternal(AndroidKeystoreAesGcm.java:118)
                                         	at com.google.crypto.tink.integration.android.AndroidKeystoreAesGcm.decrypt(AndroidKeystoreAesGcm.java:101)
                                         	at com.google.crypto.tink.KeysetHandle.decrypt(KeysetHandle.java:919)
                                         	at com.google.crypto.tink.KeysetHandle.readWithAssociatedData(KeysetHandle.java:804)
                                         	at com.google.crypto.tink.KeysetHandle.read(KeysetHandle.java:785)
                                         	at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.readMasterkeyDecryptAndParseKeyset(AndroidKeysetManager.java:381)
                                         	at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.build(AndroidKeysetManager.java:297)
                                         	at androidx.security.crypto.EncryptedSharedPreferences.create(EncryptedSharedPreferences.java:169)
                                         	at androidx.security.crypto.EncryptedSharedPreferences.create(EncryptedSharedPreferences.java:130)
                                         	at io.easyprefs.secure.EncryptedPref.getPreferences(EncryptedPref.kt:28)
                                         	at io.easyprefs.impl.PrefProvider.getPref(PrefProvider.kt:22)
                                         	at io.easyprefs.impl.EasyPrefImpl.read(EasyPrefImpl.kt:34)
                                         	at io.easyprefs.impl.SecurePrefImpl.read(SecurePrefImpl.kt:57)
                                         	at io.easyprefs.impl.SecurePrefImpl.read(SecurePrefImpl.kt:44)
                                         	at com.demo.mob.ui.login.LoginFragment.showBiometricLoginOption(LoginFragment.kt:155)
                                         	at com.demo.mob.ui.login.LoginFragment.setUpView(LoginFragment.kt:99)
                                         	at com.demo.mob.ui.login.LoginFragment.onCreateView(LoginFragment.kt:60)
                                         	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:3114)
                                         	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:557)
                                         	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:272)
                                         	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1943)
                                         	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1839)
                                         	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1782)
                                         	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:565)
                                         	at android.os.Handler.handleCallback(Handler.java:958)
                                         	at android.os.Handler.dispatchMessage(Handler.java:99)
                                         	at android.os.Looper.loopOnce(Looper.java:230)
                                         	at android.os.Looper.loop(Looper.java:319)
                                         	at android.app.ActivityThread.main(ActivityThread.java:8906)
                                         	at java.lang.reflect.Method.invoke(Native Method) 
                                         	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608) 
                                         	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103) 
                                         Caused by: android.security.KeyStoreException: Signature/MAC verification failed (internal Keystore code: -30 message: system/security/keystore2/src/operation.rs:850: KeystoreOperation::finish
                                         
                                         Caused by:
                                             0: system/security/keystore2/src/operation.rs:426: Finish failed.
                                             1: Error::Km(r#VERIFICATION_FAILED)) (public error code: 10 internal Keystore code: -30)
                                         	at android.security.KeyStore2.getKeyStoreException(KeyStore2.java:435)
                                         	at android.security.KeyStoreOperation.handleExceptions(KeyStoreOperation.java:78)
                                         	at android.security.KeyStoreOperation.finish(KeyStoreOperation.java:128)
                                         	at android.security.keystore2.KeyStoreCryptoOperationChunkedStreamer$MainDataStream.finish(KeyStoreCryptoOperationChunkedStreamer.java:228)
                                         	at android.security.keystore2.KeyStoreCryptoOperationChunkedStreamer.doFinal(KeyStoreCryptoOperationChunkedStreamer.java:181)
10:42:17.584 AndroidRuntime           E  	at android.security.keystore2.AndroidKeyStoreAuthenticatedAESCipherSpi$BufferAllOutputUntilDoFinalStreamer.doFinal(AndroidKeyStoreAuthenticatedAESCipherSpi.java:396)
                                         	at android.security.keystore2.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:624)
                                         	... 33 more

**Comment by kishandonga** [comment]
Sure, I will check and update here

**Comment by amzer-nazeer** [comment]
Any update on this issue? I am facing the same issue

**Comment by udayTechnosouls** [comment]
@amzer-nazeer update manifest file with  **android:allowBackup="false"** and it is resolved.
